### ISSUE TITLE
Remove student-created empty grades from Submission History view

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2875] opened 2017-01-17 16:30 UTC
We currently have a few places where students are still creating empty grade objects. That's showing an awkward element in the Submission History feature that has them creating the grade.

We should filter out the display of these empty objects.

**Comment by jwright** [comment] 2017-01-24 21:47
Duplicate of #2901

**Closed** 2017-01-24 21:47 UTC
Labels: Bug, ready
